#! /bin/sh
# prerm script for reed

set -e

case "$1" in
    remove|upgrade|deconfigure)
	update-alternatives --remove pager /usr/bin/reed
        ;;
    failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

#DEBHELPER#

exit 0


